### ISSUE TITLE
Debug Docker flowjoai-inference missing packages/errors

### ISSUE THREAD

**Issue by velazqum1** [RaiderSoft/flowjoai#20]
When launching the inference Docker image, there was an error with finding the inference.py file. The inference Pytorch AWS image has a path to find the inference.py, there seemed to be an error finding the file withing the inference image. This needs to be fixed and any packages have to be resolved or added to the Docker image and rebuilt.

**Comment by bmosier** [comment]
I'm taking ownership of this ticket but I'm going to need some help. Where do we begin the build process? Where do the base images come from? How do we test?

I would like to also document whatever docker build process we adopt.
