### ISSUE TITLE
CloudFormation template - API Gateway

### ISSUE THREAD

**Issue by winee-design** [RaiderSoft/flowjoai#4]
As a developer, I want a document that showcases the AWS infrastructure of our API Gateway and allows for a reproducible and automated deployment process.

**Comment by bmosier** [comment]
How about also:
As an engineer, I would like a reproducible and automated deployment process for the API gateway.

**Comment by bmosier** [comment]
Something like this? https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html

**Comment by winee-design** [comment]
I'll take this
